dict_type: sys_sub_item_type
dict_name: 商品类型
source_table: test_order
generated_at: '2026-03-28T17:31:45.852934'
data:
- label: 实物商品
  value: '1'
  sort: 1
  is_default: Y
  list_class: primary
  status: '0'
- label: 虚拟商品
  value: '2'
  sort: 2
  is_default: N
  list_class: info
  status: '0'
